# Generated by Django 5.2.14 on 2026-05-21 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mouse",
            name="coat_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mice",
                to="colony.coatcolor",
            ),
        ),
        migrations.AddField(
            model_name="mouse",
            name="genotype",
            field=models.ManyToManyField(
                blank=True, related_name="mice", to="colony.genotypetag"
            ),
        ),
        migrations.AddField(
            model_name="mouse",
            name="mouse_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mice",
                to="colony.mouseline",
            ),
        ),
        migrations.AddField(
            model_name="mouse",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mice",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mouse",
            name="phenotype",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="mouse",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mice",
                to="colony.protocol",
            ),
        ),
    ]
