# Generated by Django 5.2.14 on 2026-05-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0002_mouse_coat_color_mouse_genotype_mouse_mouse_line_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "female",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mated_as_female",
                        to="colony.mouse",
                    ),
                ),
                (
                    "male",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mated_as_male",
                        to="colony.mouse",
                    ),
                ),
            ],
        ),
    ]
