# Generated by Django 5.2.14 on 2026-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0004_mouse_alt_id_alter_mouse_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouse",
            name="alt_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("L", "L"),
                    ("R", "R"),
                    ("LL", "LL"),
                    ("RR", "RR"),
                    ("LR", "LR"),
                    ("LLR", "LLR"),
                    ("LRR", "LRR"),
                    ("LLRR", "LLRR"),
                    ("LLL", "LLL"),
                    ("RRR", "RRR"),
                    ("LLLR", "LLLR"),
                    ("LLLRR", "LLLRR"),
                    ("LLLLRRR", "LLLRRR"),
                    ("LRRR", "LRRR"),
                    ("LLRRR", "LLRRR"),
                ],
                max_length=7,
                null=True,
            ),
        ),
    ]
