# Generated by Django 5.2.14 on 2026-05-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0005_alter_mouse_alt_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Litter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField()),
                ("notes", models.CharField()),
                (
                    "mating_pair",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="litters",
                        to="colony.matingpair",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mouse",
            name="litter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pups",
                to="colony.litter",
            ),
        ),
    ]
