# Generated by Django 5.2.14 on 2026-05-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0006_litter_mouse_litter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouse",
            name="tag",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
