# Generated by Django 5.2.14 on 2026-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0007_alter_mouse_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="litter",
            name="notes",
            field=models.CharField(blank=True, null=True),
        ),
    ]
