# Generated by Django 5.2.14 on 2026-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0008_alter_litter_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="litter",
            name="notes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
