# Generated by Django 5.2.14 on 2026-05-28 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0009_alter_litter_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="litter",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="litters_on_protocol",
                to="colony.protocol",
            ),
        ),
    ]
