# Generated by Django 5.2.14 on 2026-05-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0010_litter_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouseline",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
