# Generated by Django 5.2.14 on 2026-05-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0011_alter_mouseline_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MouseGenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zygosity",
                    models.CharField(
                        choices=[
                            ("HET", "Heterozygous"),
                            ("HOM", "Homozygous"),
                            ("WT", "Wild Type"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "mouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genotype_entries",
                        to="colony.mouse",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colony.genotypetag",
                    ),
                ),
            ],
            options={
                "unique_together": {("mouse", "tag")},
            },
        ),
    ]
