# Generated by Django 5.2.14 on 2026-05-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0012_mousegenotype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cage_id", models.CharField(blank=True, max_length=10, unique=True)),
                (
                    "cage_location",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                (
                    "mating_pair",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cage",
                        to="colony.matingpair",
                    ),
                ),
            ],
        ),
    ]
