# Generated by Django 5.2.14 on 2026-05-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0013_cage"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouse",
            name="cage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="colony.cage",
            ),
        ),
    ]
