# Generated by Django 5.2.14 on 2026-06-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0014_mouse_cage'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colony.cage'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='status',
            field=models.CharField(choices=[('alive', 'Alive'), ('breeder', 'Reserved for breeding'), ('vet', 'Under vet surveillance'), ('dead', 'Dead')], default='alive', max_length=20),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('birth', 'Birth'), ('move', 'Cage move'), ('matting', 'Mating'), ('litter', 'Litter'), ('status', 'Status change'), ('vet', 'Vet care'), ('EEG Surgery', 'EEG surgery experiment'), ('EEG rec', 'EEG recording'), ('sleep dep', 'Sleep deprivation experiment'), ('Sleep rec', 'Sleep recording'), ('Injury', 'Injury'), ('death', 'Death'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('pup_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of pups (for litter events)', null=True)),
                ('new_status', models.CharField(blank=True, choices=[('birth', 'Birth'), ('move', 'Cage move'), ('matting', 'Mating'), ('litter', 'Litter'), ('status', 'Status change'), ('vet', 'Vet care'), ('EEG Surgery', 'EEG surgery experiment'), ('EEG rec', 'EEG recording'), ('sleep dep', 'Sleep deprivation experiment'), ('Sleep rec', 'Sleep recording'), ('Injury', 'Injury'), ('death', 'Death'), ('other', 'Other')], help_text='New.mouse status (for status change events)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Experiment details, vet notes, injury description, etc.')),
                ('cage', models.ForeignKey(blank=True, help_text='Destination cage for a move event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='colony.cage')),
                ('litter', models.ForeignKey(blank=True, help_text='Litter event (link to litter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='colony.litter')),
                ('mating_pair', models.ForeignKey(blank=True, help_text='Mating event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='colony.matingpair')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='colony.mouse')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
    ]
