# Generated by Django 5.2.14 on 2026-07-21 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0015_litter_cage_mouse_status_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['date', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='history',
            name='mating_pair',
        ),
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='history',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='colony.cage'),
        ),
        migrations.AlterField(
            model_name='history',
            name='event',
            field=models.CharField(choices=[('birth', 'Birth'), ('move', 'Cage move'), ('mating', 'Mating'), ('litter', 'Litter'), ('status', 'Status change'), ('vet', 'Vet care'), ('eeg_surg', 'EEG surgery experiment'), ('eeg_rec', 'EEG recording'), ('sleep_dep', 'Sleep deprivation experiment'), ('sleep_rec', 'Sleep recording'), ('injury', 'Injury'), ('death', 'Death'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='colony.litter'),
        ),
        migrations.AlterField(
            model_name='history',
            name='new_status',
            field=models.CharField(blank=True, choices=[('alive', 'Alive'), ('breeder', 'Reserved for breeding'), ('vet', 'Under vet surveillance'), ('dead', 'Dead')], max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='pup_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='litter',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='colony.cage'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mice', to='colony.cage'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pups', to='colony.litter'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='protocol',
            field=models.ForeignKey(blank=True, default='4606', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mice', to='colony.protocol'),
        ),
    ]
