# Generated by Django 5.2.14 on 2026-06-01 19:10

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('lookup', models.CharField(blank=True, max_length=50, null=True)),
                ('rep', models.CharField(blank=True, max_length=30, null=True)),
                ('rep_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('rep_email', models.CharField(blank=True, max_length=30, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('lookup', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('rep', models.CharField(blank=True, max_length=30, null=True)),
                ('rep_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('rep_email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('placed_on', models.DateField(db_comment='Date and time the order was placed, default=Now()', db_default=django.db.models.functions.datetime.Now())),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chemical_formula', models.CharField(blank=True, max_length=50, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacturer_number', models.CharField(blank=True, max_length=30, null=True)),
                ('size_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(blank=True, choices=[('L', 'Liter'), ('g', 'Grams'), ('kg', 'Kilograms'), ('lbs', 'Pounds')], max_length=15, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
            ],
        ),
    ]
