# Generated by Django 5.2.14 on 2026-07-21 18:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='chemical_formula',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='manufacturer_number',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order_items',
        ),
        migrations.AddField(
            model_name='item',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='chemical_formula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.manufacturer'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('pending', 'pending')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='full_amount',
            field=models.DecimalField(blank=True, db_comment='price x quantity', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_set', to='inventory.order'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='price',
            field=models.CharField(blank=True, db_comment='$$', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='lookup',
            field=models.CharField(blank=True, db_comment='Lookup url for item search', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_on',
            field=models.DateField(db_comment='default=Now()', default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='unit',
            field=models.CharField(blank=True, choices=[('/box', 'per box'), ('/case', 'per case'), ('/pack', 'per pack'), ('/pair', 'per pair'), ('/rod', 'per rod'), ('Gal', 'Gallons'), ('L', 'Litters'), ('U', 'Units'), ('cm', 'Centimiters'), ('sq ft', 'Square feet'), ('cubic ft', 'Cubic feet'), ('cubic yd', 'Cubic yards'), ('each', 'Each'), ('ft', 'Feet'), ('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds'), ('m', 'Meters'), ('mL', 'Milliliters'), ('mg', 'Milligrams'), ('mm', 'Millimiters'), ('oz', 'Onces'), ('pieces', 'Pieces'), ('rxns', 'rxns'), ('samples', 'samples'), ('yd', 'Yards'), ('µg', 'Micrograms'), ('µL', 'Microlitters')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='lookup',
            field=models.CharField(blank=True, db_comment='Lookup url for item search', max_length=50, null=True),
        ),
    ]
